site_name: Omnibenchmark
site_url: https://example.com/
nav:
    - Motivation: 01_landing.md
    - Getting started: 
        - start/index.md
        - Data modules: start/01_data_module.md
    - How-to guides: 
        - how_to/index.md
        - Build object: how_to/01_build_object.md
        - Create dataset: how_to/02_create_dataset.md
    - About: about.md

theme:
    name: material
    features:
    - navigation.indexes
